version: '3.8'
services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=sqlite:///database/app.db
      - SECRET_KEY=kiba-insecure-secret
  frontend:
    build: ./frontend
    working_dir: /app
    command: npm run dev -- --host
    ports:
      - "5173:5173"
