"""Crear tablas iniciales y confirmaciones

Revision ID: 3f4319747613
Revises: 
Create Date: 2025-05-04 22:19:35.261208

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3f4319747613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('confirmaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cita_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('confirmada_en', sa.DateTime(), nullable=True))
        batch_op.alter_column('sms_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.create_foreign_key(None, 'citas', ['cita_id'], ['id'])
        batch_op.drop_column('confirmado')
        batch_op.drop_column('fecha_confirmacion')

    with op.batch_alter_table('sms', schema=None) as batch_op:
        batch_op.alter_column('mensaje',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['token_confirmacion'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sms', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('mensaje',
               existing_type=mysql.TEXT(),
               nullable=True)

    with op.batch_alter_table('confirmaciones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_confirmacion', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True))
        batch_op.add_column(sa.Column('confirmado', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('sms_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('confirmada_en')
        batch_op.drop_column('cita_id')

    # ### end Alembic commands ###
